#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmpdclient
Version  : 2.16
Release  : 1
URL      : https://github.com/MusicPlayerDaemon/libmpdclient/archive/v2.16.tar.gz
Source0  : https://github.com/MusicPlayerDaemon/libmpdclient/archive/v2.16.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: libmpdclient-data = %{version}-%{release}
Requires: libmpdclient-lib = %{version}-%{release}
BuildRequires : buildreq-meson

%description
libmpdclient
============
libmpdclient is a C library which implements the `Music Player Daemon
<http://www.musicpd.org/>`__ protocol.

%package data
Summary: data components for the libmpdclient package.
Group: Data

%description data
data components for the libmpdclient package.


%package dev
Summary: dev components for the libmpdclient package.
Group: Development
Requires: libmpdclient-lib = %{version}-%{release}
Requires: libmpdclient-data = %{version}-%{release}
Provides: libmpdclient-devel = %{version}-%{release}
Requires: libmpdclient = %{version}-%{release}

%description dev
dev components for the libmpdclient package.


%package doc
Summary: doc components for the libmpdclient package.
Group: Documentation

%description doc
doc components for the libmpdclient package.


%package lib
Summary: lib components for the libmpdclient package.
Group: Libraries
Requires: libmpdclient-data = %{version}-%{release}

%description lib
lib components for the libmpdclient package.


%prep
%setup -q -n libmpdclient-2.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570966331
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/vala/vapi/libmpdclient.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/mpd/async.h
/usr/include/mpd/audio_format.h
/usr/include/mpd/capabilities.h
/usr/include/mpd/client.h
/usr/include/mpd/compiler.h
/usr/include/mpd/connection.h
/usr/include/mpd/database.h
/usr/include/mpd/directory.h
/usr/include/mpd/entity.h
/usr/include/mpd/error.h
/usr/include/mpd/idle.h
/usr/include/mpd/list.h
/usr/include/mpd/message.h
/usr/include/mpd/mixer.h
/usr/include/mpd/mount.h
/usr/include/mpd/output.h
/usr/include/mpd/pair.h
/usr/include/mpd/parser.h
/usr/include/mpd/password.h
/usr/include/mpd/player.h
/usr/include/mpd/playlist.h
/usr/include/mpd/protocol.h
/usr/include/mpd/queue.h
/usr/include/mpd/recv.h
/usr/include/mpd/response.h
/usr/include/mpd/search.h
/usr/include/mpd/send.h
/usr/include/mpd/settings.h
/usr/include/mpd/socket.h
/usr/include/mpd/song.h
/usr/include/mpd/stats.h
/usr/include/mpd/status.h
/usr/include/mpd/sticker.h
/usr/include/mpd/tag.h
/usr/include/mpd/version.h
/usr/lib64/libmpdclient.so
/usr/lib64/pkgconfig/libmpdclient.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libmpdclient/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmpdclient.so.2
/usr/lib64/libmpdclient.so.2.16
